"use client";
import {useEffect,useMemo,useState} from "react";
import {Activity,AlertTriangle,CheckCircle2,CreditCard,LayoutDashboard,LogOut,Menu,Users,Wallet,X} from "lucide-react";
type Provider={id:string;fullName:string;phone:string;status:string;service:string;subscriptionEndsAt:string|null};
type Payment={id:string;amount:number;status:string;method:string;provider:string;createdAt:string};
type Data={stats:{providers:number;active:number;blocked:number;pendingPayments:number;revenue:number};services:{name:string;active:number;max:number}[];providers:Provider[];payments:Payment[]};
export default function Dashboard(){const[open,setOpen]=useState(false);const[data,setData]=useState<Data|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
useEffect(()=>{fetch("/api/dashboard").then(r=>{if(!r.ok)throw new Error("Dashboard access denied");return r.json()}).then(setData).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
const currency=(n:number)=>new Intl.NumberFormat("en-RW",{style:"currency",currency:"RWF",maximumFractionDigits:0}).format(n);
return <main className="dash"><aside className={open?"sidebar open":"sidebar"}><div className="dash-brand"><span className="mark"><LayoutDashboard size={18}/></span><b>BOOKING ADMIN</b></div><nav><a className="active"><LayoutDashboard size={17}/> Dashboard</a><a><Users size={17}/> Providers</a><a><CreditCard size={17}/> Payments</a><a><Activity size={17}/> Services</a></nav><button className="logout"><LogOut size={17}/> Logout</button></aside>
<div className="dash-main"><header className="dash-head"><div><button className="dash-menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><small>PRIVATE ADMIN AREA</small><h1>Dashboard</h1></div><span className="admin-badge">Admin</span></header>
{loading?<div className="loading">Loading dashboard...</div>:error?<div className="error-box"><AlertTriangle size={20}/>{error}</div>:data&&<><section className="stat-grid"><div><span className="stat-icon"><Users/></span><small>Total Providers</small><strong>{data.stats.providers}</strong></div><div><span className="stat-icon active-icon"><CheckCircle2/></span><small>Active Providers</small><strong>{data.stats.active}</strong></div><div><span className="stat-icon blocked-icon"><AlertTriangle/></span><small>Blocked Providers</small><strong>{data.stats.blocked}</strong></div><div><span className="stat-icon pay-icon"><Wallet/></span><small>Revenue</small><strong>{currency(data.stats.revenue)}</strong></div></section>
<section className="dash-grid"><div className="panel"><div className="panel-head"><div><small>SERVICE CAPACITY</small><h2>Providers by service</h2></div></div><div className="service-list">{data.services.map(s=><div className="service-capacity" key={s.name}><div><b>{s.name}</b><span>{s.active}/{s.max} active</span></div><div className="bar"><i style={{width:(s.active/s.max)*100+"%"}}/></div></div>)}</div></div>
<div className="panel"><div className="panel-head"><div><small>PAYMENTS</small><h2>Recent payments</h2></div></div><div className="mini-list">{data.payments.slice(0,6).map(p=><div className="mini-row" key={p.id}><span className="mini-avatar"><CreditCard size={15}/></span><div><b>{p.provider}</b><small>{p.method}</small></div><strong>{currency(p.amount)}</strong><em className={p.status.toLowerCase()}>{p.status}</em></div>)}</div></div></section>
<section className="panel"><div className="panel-head"><div><small>PROVIDERS</small><h2>Latest providers</h2></div></div><div className="table-wrap"><table><thead><tr><th>Name</th><th>Service</th><th>Phone</th><th>Status</th><th>Subscription</th></tr></thead><tbody>{data.providers.map(p=><tr key={p.id}><td><b>{p.fullName}</b></td><td>{p.service}</td><td>{p.phone}</td><td><span className={"status "+p.status.toLowerCase()}>{p.status}</span></td><td>{p.subscriptionEndsAt?new Date(p.subscriptionEndsAt).toLocaleDateString():"—"}</td></tr>)}</tbody></table></div></section></>}</div></main>}